spring:
  application:
    name: Dara Hotel
  datasource:
    url : jdbc:postgresql://localhost:5432/hotel
    username: darahotel
    password: darahotel
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
      dialect:  org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
#  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    format:
      date-time: yyyy-MM-dd HH:mm:ss
