databaseChangeLog:
  - changeSet:
      id: 010_init_db_user_security
      author: daralon2020@gmail.com
      changes:
        - createTable:
            tableName: user
            columns:
              - column:
                  name: id
                  type: BIGINT
                  constraints:
                    primaryKey: true
                  autoIncrement: true
              - column:
                  name: first_name
                  type: VARCHAR(100)
              - column:
                  name: last_name
                  type: VARCHAR(100)
              - column:
                  name: email
                  type: VARCHAR(100)
              - column:
                  name: password
                  type: VARCHAR(100)
              - column:
                  name: role
                  type: VARCHAR(100)